Add EndpointSlice and new policy fields to syncer
projectcalico/libcalico-go pull request #1443
Opened 2021-06-30 20:53 UTC by caseydavenport

## Description

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

2021-07-01 08:55 UTC, fasaxc requested changes
Generally looking good to me

2021-07-01 08:55 UTC, fasaxc commented on lib/validator/v3/validator.go
> +	// Services are only allowed on egress rules.
Think we should also prevent services in the egress Destination struct

2021-07-01 08:55 UTC, fasaxc commented on lib/validator/v3/validator_test.go
> +
Worth shooting for full coverage in the validation logic; think there are a few more cases to cover

2021-07-19 21:55 UTC, caseydavenport commented
@fasaxc I think this is ready for another look.

Also @mgleung this is the next part of the PR you reviewed today

2021-07-21 18:00 UTC, mgleung commented on lib/validator/v3/validator.go
> +	// Services are only allowed on egress rules.
Do we not also need to check that services are not set as the source on the egress rules for the GNP?

2021-07-21 23:29 UTC, mgleung approved these changes
LGTM

2021-07-22 18:28 UTC, merged